happy/urls.py
from django.urls import include, path
from . import views

app_name = 'happy'

urlpatterns = [
    path('', views.home, name='home'),
    path('watch/', views.watch, name='watch'),
    path('games/', views.games, name='games'),
    path('music/', views.music, name='music'),
    path('search/', views.searchKeyword, name='searchKeyword'),
    path('detail/<str:detail_id>/', views.detail, name='detail'),
    path('netflix/', views.netflix, name='netflix'),
    path('deleteNetflix/<int:delete_id>/', views.deleteNetflix, name='deleteNetflix'),
    path('anime/', views.anime, name='anime'),
    path('deleteAnime/<int:delete_id>/', views.deleteAnime, name='deleteAnime'),
    path('kdrama/', views.kdrama, name='kdrama'),
    path('deleteKdrama/<int:delete_id>/', views.deleteKdrama, name='deleteKdrama'),
    path('romantic/', views.romantic, name='romantic'),
    path('deleteRomantic/<int:delete_id>/', views.deleteRomantic, name='deleteRomantic'),
    path('tiktok/', views.tiktok, name='tiktok'),
    path('deleteTiktok/<int:delete_id>/', views.deleteTiktok, name='deleteTiktok'),
    path('podcast/', views.podcast, name='podcast'),
    path('deletePodcast/<int:delete_id>/', views.deletePodcast, name='deletePodcast'),
    path('kpop/', views.kpop, name='kpop'),
    path('deleteKpop/<int:delete_id>/', views.deleteKpop, name='deleteKpop'),
    path('games1/', views.games1, name='games1'),
    path('deleteGames1/<int:delete_id>/', views.deleteGames1, name='deleteGames1'),
    path('games2/', views.games2, name='games2'),
    path('deleteGames2/<int:delete_id>/', views.deleteGames2, name='deleteGames2'),
    # dilanjutkan ...
]

home/urls.py
from django.urls import include, path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name = 'register'),
    path('logout/', views.view_logout, name = 'logout')
]

staces/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('todo/', include(('todo.urls', 'todo'), namespace='todo')),
    path('happy/', include(('happy.urls', 'happy'), namespace='happy')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('foryou/', include(('foryou.urls', 'foryou'), namespace='foryou')),
    path('', include('main.urls')),
]

happy/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    foto = models.CharField(max_length=100, null=True)
    keyword = models.TextField()

    def __str__(self):
        return self.name

class Comment(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

class CommentKdrama(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

class CommentAnime(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

class CommentRomantic(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

class CommentKpop(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

class CommentPodcast(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

class CommentTiktok(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

class CommentGames1(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

class CommentGames2(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.author

home/models.py
from django.db import models

# Create your models here.

happy/forms.py
from django import forms 
 
class CommentForm(forms.Form):
    author = forms.CharField(
        label = "Name",
        widget = forms.TextInput(
            attrs = {
                'class':'form-control',
                'max_length : 100'
                'id' : 'name',
                'placeholder' : 'Name',
            }
        )
    )

    email = forms.CharField(
        label = "Email",
        widget = forms.TextInput(
            attrs = {
                'class':'form-control',
                'max_length : 100'
                'id' : 'email',
                'placeholder' : 'Email',
            }
        )
    )

    content = forms.CharField(
        label = "Write Comment",
        widget = forms.Textarea(
            attrs = {
                'class':'form-control w-100',
                'max_length : 100'
                'cols' : '30',
                'rows' : '10',
                'id' : 'content',
                'placeholder' : 'Write Comment',
            }
        )
    )

class SearchForm(forms.Form):
    input = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class':'form-control',
                'max_length : 100'
                'id' : 'search',
                'placeholder' : 'Search Keyword',
            }
        )
    )

home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]

happy/views.py
from django.shortcuts import render, redirect 
from .models import Article, Comment, CommentKdrama, CommentPodcast, CommentAnime, CommentKpop, CommentRomantic, CommentGames1, CommentGames2, CommentTiktok
from . import forms

# Create your views here.
def home(request):
    return render(request, 'home.html')

def watch(request):
    return render(request, 'watch.html')

def music(request):
    return render(request, 'music.html')

def games(request):
    return render(request, 'games.html')

# ======================================

def searchKeyword(request):
    word = request.GET.get('search_keyword')
    object_list = Article.objects.filter(keyword__icontains=word)
    return render(request, 'searchView.html', {'list':object_list}) 

def detail(request, detail_id):
    blog_detail = Article.objects.get(name = detail_id)
    if blog_detail.name == 'netflix':
        return redirect('/happy/netflix')
    elif blog_detail.name == 'kdrama':
        return redirect('/happy/kdrama')
    elif blog_detail.name == 'romantic':
        return redirect('/happy/romantic')
    elif blog_detail.name == 'anime':
        return redirect('/happy/anime')
    elif blog_detail.name == 'tiktok':
        return redirect('/happy/tiktok')
    elif blog_detail.name == 'podcast':
        return redirect('/happy/podcast')
    elif blog_detail.name == 'kpop':
        return redirect('/happy/kpop')
    elif blog_detail.name == 'games1':
        return redirect('/happy/games1')
    elif blog_detail.name == 'games2':
        return redirect('/happy/games2')
    else:
        return redirect('')

# ======================================

def netflix(request):
    comment_form = forms.CommentForm()
    if request.method ==  'POST':
        comment_form_input = forms.CommentForm(request.POST)
        if comment_form_input.is_valid():
            data = comment_form_input.cleaned_data
            comment_input = Comment()
            comment_input.author = data['author'] 
            comment_input.email = data['email'] 
            comment_input.content = data['content']
            comment_input.save()
            #current_data = Comment.objects.all()

            return redirect('/happy/netflix')   
        else:
            current_data = Comment.objects.all()
            return render(request, 'netflix.html', {'form':comment_form, 'status':'failed', 'data':current_data})      
    else:
        current_data = Comment.objects.all()
        return render(request, 'netflix.html', {'form':comment_form, 'data':current_data})      

def deleteNetflix(request, delete_id):
    try:
        deleted_subject = Comment.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/happy/netflix')
    except:
        return redirect('/happy/netflix')

def anime(request):
    comment_form = forms.CommentForm()
    if request.method ==  'POST':
        comment_form_input = forms.CommentForm(request.POST)
        if comment_form_input.is_valid():
            data = comment_form_input.cleaned_data
            comment_input = CommentAnime()
            comment_input.author = data['author'] 
            comment_input.email = data['email'] 
            comment_input.content = data['content']
            comment_input.save()
            #current_data = Comment.objects.all()

            return redirect('/happy/anime')   
        else:
            current_data = CommentAnime.objects.all()
            return render(request, 'anime.html', {'form':comment_form, 'status':'failed', 'data':current_data})      
    else:
        current_data = CommentAnime.objects.all()
        return render(request, 'anime.html', {'form':comment_form, 'data':current_data})

def deleteAnime(request, delete_id):
    try:
        deleted_subject = CommentAnime.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/happy/anime')
    except:
        return redirect('/happy/anime')


def kdrama(request):
    comment_form = forms.CommentForm()
    if request.method ==  'POST':
        comment_form_input = forms.CommentForm(request.POST)
        if comment_form_input.is_valid():
            data = comment_form_input.cleaned_data
            comment_input = CommentKdrama()
            comment_input.author = data['author'] 
            comment_input.email = data['email'] 
            comment_input.content = data['content']
            comment_input.save()
            #current_data = Comment.objects.all()

            return redirect('/happy/kdrama')   
        else:
            current_data = CommentKdrama.objects.all()
            return render(request, 'kdrama.html', {'form':comment_form, 'status':'failed', 'data':current_data})      
    else:
        current_data = CommentKdrama.objects.all()
        return render(request, 'kdrama.html', {'form':comment_form, 'data':current_data})      

def deleteKdrama(request, delete_id):
    try:
        deleted_subject = CommentKdrama.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/happy/kdrama')
    except:
        return redirect('/happy/kdrama')

def podcast(request):
    comment_form = forms.CommentForm()
    if request.method ==  'POST':
        comment_form_input = forms.CommentForm(request.POST)
        if comment_form_input.is_valid():
            data = comment_form_input.cleaned_data
            comment_input = CommentPodcast()
            comment_input.author = data['author'] 
            comment_input.email = data['email'] 
            comment_input.content = data['content']
            comment_input.save()
            #current_data = Comment.objects.all()

            return redirect('/happy/podcast')   
        else:
            current_data = CommentPodcast.objects.all()
            return render(request, 'podcast.html', {'form':comment_form, 'status':'failed', 'data':current_data})      
    else:
        current_data = CommentPodcast.objects.all()
        return render(request, 'podcast.html', {'form':comment_form, 'data':current_data})      

def deletePodcast(request, delete_id):
    try:
        deleted_subject = CommentPodcast.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/happy/podcast')
    except:
        return redirect('/happy/podcast')

def kpop(request):
    comment_form = forms.CommentForm()
    if request.method ==  'POST':
        comment_form_input = forms.CommentForm(request.POST)
        if comment_form_input.is_valid():
            data = comment_form_input.cleaned_data
            comment_input = CommentKpop()
            comment_input.author = data['author'] 
            comment_input.email = data['email'] 
            comment_input.content = data['content']
            comment_input.save()
            #current_data = Comment.objects.all()

            return redirect('/happy/kpop')   
        else:
            current_data = CommentKpop.objects.all()
            return render(request, 'kpop.html', {'form':comment_form, 'status':'failed', 'data':current_data})      
    else:
        current_data = CommentKpop.objects.all()
        return render(request, 'kpop.html', {'form':comment_form, 'data':current_data})      

def deleteKpop(request, delete_id):
    try:
        deleted_subject = CommentKpop.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/happy/kpop')
    except:
        return redirect('/happy/kpop')

def games1(request):
    comment_form = forms.CommentForm()
    if request.method ==  'POST':
        comment_form_input = forms.CommentForm(request.POST)
        if comment_form_input.is_valid():
            data = comment_form_input.cleaned_data
            comment_input = CommentGames1()
            comment_input.author = data['author'] 
            comment_input.email = data['email'] 
            comment_input.content = data['content']
            comment_input.save()
            #current_data = Comment.objects.all()

            return redirect('/happy/games1')   
        else:
            current_data = CommentGames1.objects.all()
            return render(request, 'games1.html', {'form':comment_form, 'status':'failed', 'data':current_data})      
    else:
        current_data = CommentGames1.objects.all()
        return render(request, 'games1.html', {'form':comment_form, 'data':current_data})      

def deleteGames1(request, delete_id):
    try:
        deleted_subject = CommentGames1.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/happy/games1')
    except:
        return redirect('/happy/games1')

def games2(request):
    comment_form = forms.CommentForm()
    if request.method ==  'POST':
        comment_form_input = forms.CommentForm(request.POST)
        if comment_form_input.is_valid():
            data = comment_form_input.cleaned_data
            comment_input = CommentGames2()
            comment_input.author = data['author'] 
            comment_input.email = data['email'] 
            comment_input.content = data['content']
            comment_input.save()
            #current_data = Comment.objects.all()

            return redirect('/happy/games2')   
        else:
            current_data = CommentGames2.objects.all()
            return render(request, 'games2.html', {'form':comment_form, 'status':'failed', 'data':current_data})      
    else:
        current_data = CommentGames2.objects.all()
        return render(request, 'games2.html', {'form':comment_form, 'data':current_data})      

def deleteGames2(request, delete_id):
    try:
        deleted_subject = CommentGames2.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/happy/games2')
    except:
        return redirect('/happy/games2')

def romantic(request):
    comment_form = forms.CommentForm()
    if request.method ==  'POST':
        comment_form_input = forms.CommentForm(request.POST)
        if comment_form_input.is_valid():
            data = comment_form_input.cleaned_data

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import RegisForm
from django.utils.safestring import mark_safe

# Create your views here.

def index(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

        else :
            messages.error(request,'Username or password not correct')

    return render(request, 'index.html')

def register(request):
    if request.method == "POST":
        form = RegisForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Congratulations, your account has been successfully created! Please Kindly Login on the Login Button')
        else :
            messages.error(request, mark_safe("ERROR: Something went wrong. User Registration failed<br/>Requirements:<br/>1. Username required 150 characters or fewer. Letters, digits, and @/./+/-/_ only.<br/>2. Enter the same password as before<br/>3. Your password must contain at least 8 character<br/>4. Your password can't be a commonly used password, entirely numeric, and similiarlu to username"))

    else :
        form = RegisForm()
    return render(request, 'register.html', {'form' : form})

def view_logout(request):
    logout(request)
    return redirect('/')

happy/templates/baseHappy.html
<!doctype html>

{% extends "navbarHappy.html" %}

{% block head %}
<html class="no-js" lang="zxx">

{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Abril+Fatface"/>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Happy Space </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">

<!-- CSS here -->
    <link rel="stylesheet" href="{% static 'happy/cssHappy/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/slick.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/styleHappy.css' %}">
    <link rel="stylesheet" href="{% static 'happy/cssHappy/responsive.css' %}">  
</head>

<body>

<!-- Preloader Start -->
    <!-- slider Area Start-->
    <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'happy/imgHappy/tk1/happy.png' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap">
                            <h2>Happy Space!</h2>
                            <br></br>
                            <p>This is a relaxing space to clear your mind after went through the day.<br>
                            There will be various categories of entertainment that you can do at home.<br>
                            The categories are music, movies, and games. Each category will be presented<br>
                            with articles containing recommendations along with a brief description.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->

{% block content %}
{% endblock %}
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                                <li>
                                    <a href="{% url 'happy:home' %}" class="d-flex">
                                        <p>What to do?</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'happy:watch' %}" class="d-flex">
                                        <p>What to watch?</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'happy:music' %}" class="d-flex">
                                        <p>Music</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'happy:games' %}" class="d-flex">
                                        <p>Games</p>
                                    </a>
                                </li>
                            </ul>
                        </aside>

                        <aside class="single_sidebar_widget search_widget">
                            <a class="d-flex">
                                <p>What is your interest?</p>
                            </a>
                            <form action="{% url 'happy:searchKeyword' %}" method="GET">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input id="search_keyword" name="search_keyword" type="text" class="form-control" placeholder='Search Keyword'
                                            onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btns" type="button"><i class="fa fa-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Search</button>
                            </form>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>

<!-- JS here -->
		<!-- All JS Custom Plugins Link Here here -->
        <script src="{% static 'happy/jsHappy/vendor/modernizr-3.5.0.min.js' %}"></script>
		<!-- Jquery, Popper, Bootstrap -->
        <script src="{% static 'happy/jsHappy/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/popper.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static 'happy/jsHappy/jquery.slicknav.min.js' %}"></script>
		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'happy/jsHappy/owl.carousel.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/slick.min.js' %}"></script>
        <!-- Date Picker -->
        <script src="{% static 'happy/jsHappy/gijgo.min.js' %}"></script>
		<!-- One Page, Animated-HeadLin -->
        <script src="{% static 'happy/jsHappy/wow.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/animated.headline.js' %}"></script>		
		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'happy/jsHappy/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/jquery.sticky.js' %}"></script>
        <script src="{% static 'happy/jsHappy/jquery.magnific-popup.js' %}"></script>
        <!-- contact js -->
        <script src="{% static 'happy/jsHappy/contact.js' %}"></script>
        <script src="{% static 'happy/jsHappy/jquery.form.js' %}"></script>
        <script src="{% static 'happy/jsHappy/jquery.validate.min.js' %}"></script>
        <script src="{% static 'happy/jsHappy/mail-script.js' %}"></script>
        <script src="{% static 'happy/jsHappy/jquery.ajaxchimp.min.js' %}"></script> 
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static 'happy/jsHappy/plugins.js' %}"></script>
        <script src="{% static 'happy/jsHappy/main.js' %}"></script>
</body>
</html>

{% endblock %}

happy/templates/navbarHappy.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="icon" href="{% static 'img/staces-logo.png' %}">
	<title>Happy Space</title>
</head>
<body>


<div id="page-wrap">
	<!-- ==========================================================================================================
													   HERO
		 ========================================================================================================== -->
		 <nav class="navbar navbar-expand-lg navbar-light main-navbar-nav1">
			<a class="navbar-brand" href="">STACES</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
		  
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav nav-items-center ml-auto mr-auto">
				<li class="nav-item">
					  <a class="nav-link" href="{% url 'home:index' %}">Home</a>
				</li>
				<li class="nav-item">
					  <a class="nav-link" href="{% url 'todo:index' %}">TO DO</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'happy:home' %}">Happy<span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'learning:index' %}">Learning</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'foryou:index' %}">For You</a>
				</li>
				{% if user.is_authenticated %}
					<a href="#">
						<div class="social-icons-header">
							<a href="/logout/">
								<button type="button" class="btn btn-md features-btn-first animated fadeInLeft wow ml-4" data-wow-delay="0.95s" style="background-color: #CDD7D6; color: #102542; border-radius: 5%; padding: 20px 10px auto; font-weight:700; font-family: 'Josefin Sans';">Log Out</button>
							  </a>
						</div>
					</a>
				{% else %}
					<a href="/#log-in">
						<div class="social-icons-header">
							<button class="btn btn-md features-btn-first animated fadeInLeft wow ml-4" data-wow-delay="0.95s" style="background-color: #CDD7D6; color: #102542; border-radius: 5%; padding: 20px 10px auto; font-weight:700; font-family: 'Josefin Sans';">Log In</button>
						</div>
					</a>
				{% endif %}
			  </ul>
			</div>
		  </nav>

	<!-- ==========================================================================================================
													  FEATURES
		 ========================================================================================================== -->

	{% block head %}
    {% endblock %}

	<!-- ==========================================================================================================
                                               FOOTER
    ========================================================================================================== -->

	<footer class="footer-outer">
		<div class="container footer-inner">

			<div class="footer-three-grid wow fadeIn animated" data-wow-delay="0.66s">
				<div>
					<nav class="footer-nav">
						<ul>
							<h1 id="h1-footer"> STACES </h1>
							<p style="color:white;">By using our website, we hope that we helped you. Stay safe, stay healthy, and stay clean!<br>
							If there is any problem, please let we know.</p>
						</ul>
						<ul>
							<div class="social-icons-footer">
								<a target="_blank" href="https://instagram.com/stacesapp/"><i class="fab fa-instagram"></i></a>
								<a target="_blank" href="mailto: stacesapp@gmail.com"><i class="fa fa-envelope"></i></i></a>
							</div>
						</ul>
						<ul>
							<p class="copyright" id="p-copyright">Copyright © 2020. All Rights Reserved</p>
						</ul>
					</nav>
				</div>
			</div>
			<span></span>
			<p class="copyright"></p>
		</div>
	</footer>

</div> <!-- main page wrapper -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>
</html>