home/urls.py
from django.urls import include, path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name = 'register'),
    path('logout/', views.view_logout, name = 'logout')
]

learning/urls.py
from django.urls import include, path
from . import views

app_name = 'learning'

urlpatterns = [
    path('', views.index, name='index'),
    path('addSource/', views.addSource, name='addSource'),
    path('programming/', views.programming, name='programming'),
    path('math/', views.math, name='math'),
    path('science/', views.science, name='science'),
    path('language/', views.language, name='language'),
    path('business/', views.business, name='business'),
    path('others/', views.others, name='others'),
    path('allSource/', views.allSource, name='allSource'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

staces/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('todo/', include(('todo.urls', 'todo'), namespace='todo')),
    path('happy/', include(('happy.urls', 'happy'), namespace='happy')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('foryou/', include(('foryou.urls', 'foryou'), namespace='foryou')),
    path('', include('main.urls')),
]

learning/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Subject(models.Model):
    name = models.CharField(max_length=100, null=True)
    category = models.ManyToManyField(Category, related_name='subjects')
    description = models.TextField(max_length=400, null=True)
    url = models.URLField(null=True)
    image = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name

main/models.py
from django.db import models

# Create your models here.

learning/forms.py
from django.forms import ModelForm
from .models import *
from django.forms.widgets import CheckboxSelectMultiple

class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        
        super(SubjectForm, self).__init__(*args, **kwargs)
        
        self.fields["category"].widget = CheckboxSelectMultiple()
        self.fields["category"].queryset = Category.objects.all()

learning/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
import random

# Create your views here.

def randomize():
    subject = set(Subject.objects.all())
    lst = random.sample(subject, 3)
    return lst

def index(request):
    subject = randomize()
    context = {'subject':subject}
    return render(request, 'main/learning.html', context)

def addSource(request):
    form = SubjectForm()
    if request.method == 'POST':
        form = SubjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/learning')
    context = {'form' : form}
    return render(request, 'main/addSource.html', context)

def divide(subject):
    lst = []
    temp = []
    for i in range(len(subject)):
        if i%3==0 and i>0:
            lst.append(temp)
            temp = []
        temp.append(subject[i])
    lst.append(temp)
    return lst

def programming(request):
    category = Category.objects.get(name='programming')
    subject = category.subjects.all()
    lst = divide(subject)
    context = {'subject' : subject, 'query' : 'Programming', 'lst':lst}
    return render(request, 'main/more.html', context)

def math(request):
    category = Category.objects.get(name='math')
    subject = category.subjects.all()
    lst = divide(subject)
    context = {'subject' : subject, 'query' : 'Math', 'lst':lst}
    return render(request, 'main/more.html', context)

def science(request):
    category = Category.objects.get(name='science')
    subject = category.subjects.all()
    lst = divide(subject)
    context = {'subject' : subject, 'query' : 'Science', 'lst':lst}
    return render(request, 'main/more.html', context)

def language(request):
    category = Category.objects.get(name='language')
    subject = category.subjects.all()
    lst = divide(subject)
    context = {'subject' : subject, 'query' : 'Language', 'lst':lst}
    return render(request, 'main/more.html', context)

def business(request):
    category = Category.objects.get(name='business')
    subject = category.subjects.all()
    lst = divide(subject)
    context = {'subject' : subject, 'query' : 'Business', 'lst':lst}
    return render(request, 'main/more.html', context)

def others(request):
    category = Category.objects.get(name='others')
    subject = category.subjects.all()
    lst = divide(subject)
    context = {'subject' : subject, 'query' : 'Others', 'lst':lst}
    return render(request, 'main/more.html', context)

def allSource(request):
    subject = Subject.objects.all()
    lst = divide(subject)
    context = {'subject' : subject, 'query' : 'All Sources', 'lst':lst}
    return render(request, 'main/more.html', context)

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

learning/templates/main/addSource.html
<!DOCTYPE html>

{% extends 'main/navfoot.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
<div id="fh5co-hero-wrapper-study-2">
{% endblock %}

{% block desc %}
<div class="animated fadeIn wow">
    <div class="container study-space-desc-2">
        <div class="study-section-title">Add Another Source</div>
    </div>
</div>
{% endblock %}

{% block content %}
<br><br>
<div class="container animated fadeIn wow">
    <form action="{% url 'learning:addSource' %}" method="POST" class="study-form" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <p style="color: #102542; font-size: 20px; font-weight:600; margin-bottom: 0;">Name*</p>
            {% render_field form.name class="form-control col-md-8" placeholder="Name" style="font-family:Josefin Sans"%}
        </div>
        <div>
            <p style="color: #102542; font-size: 20px; font-weight:600; margin-bottom: 0; margin-top: 20px;">Category*</p>
            {% for check in form.category %}
                {{check.tag}} {{check.choice_label.capitalize}} <br>
            {% endfor %}
        </div>
        <div>
            <p style="color: #102542; font-size: 20px; font-weight:600; margin-bottom: 0; margin-top: 20px;">Description*</p>
            {% render_field form.description class="form-control col-md-8" placeholder="Type a description" style="font-family:Josefin Sans"%}
        </div>
        <div>
            <p style="color: #102542; font-size: 20px; font-weight:600; margin-bottom: 0; margin-top: 20px;">URL*</p>
            {% render_field form.url class="form-control col-md-8" placeholder="https://www.url.com" style="font-family:Josefin Sans"%}
        </div> 
        <div>
            <p style="color: #102542; font-size: 20px; font-weight:600; margin-bottom: 0; margin-top: 20px;">Image URL</p>
            {% render_field form.image class="form-control col-md-8" placeholder="url with .png or .jpg suffix" style="font-family:Josefin Sans"%}
        </div> 
        <p style="color: #102542; font-size: 15px; font-weight:600; margin-bottom: 0; margin-top: 20px;">*required</p>
        <p style="color: #102542; font-size: 15px; font-weight:600; margin-bottom: 0; margin-top: 20px;">This source will be publicly displayed</p>


        <div class="pt-2 pl-2 pr-2 pb-5 col-md-3 study-site" style="text-align: center; display: flex;">
            <button type="submit" class="btn submit-button-learning p-2 spe">Submit</button>
            <a href="{% url 'learning:index' %}" class="btn submit-button-learning p-2 spe">Cancel</a>
        </div>
    </form>
</div>    
<br><br>

{% endblock %}

learning/templates/main/learning.html
{% extends 'main/navfoot.html' %}
{% load static %}

{% block desc %}
<div class="animated fadeIn wow">
    <div class="container study-space-desc">
        <div class="study-section-title">Study Space</div>
        <p class="study-section-desc">You can go all over the world to study with 
            just a browser, but what matters is that do you know where the sources are? Find out more learning sources 
            based on categories that you want to know here. There will be a short description of each 
            source to help you find what you need before going to the actual site. Lastly, you can also 
            contribute to add another learning source that might help other people with their studies.</p>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container animated fadeIn wow">
    <div class="study-subsection-title">Explore Subjects</div>
    <div class="study-container">
        <div class="study-box-1"><a href="{% url 'learning:programming' %}"><img src="{% static 'img/programming.png' %}"></a></div>
        <div class="study-box-1"><a href="{% url 'learning:math' %}"><img src="{% static 'img/math.png' %}"></a></div>
        <div class="study-box-1"><a href="{% url 'learning:science' %}"><img src="{% static 'img/science.png' %}"></a></div>
    </div>
    <div class="study-container">
        <div class="study-box-1"><a href="{% url 'learning:language' %}"><img src="{% static 'img/language.png' %}"></a></div>
        <div class="study-box-1"><a href="{% url 'learning:business' %}"><img src="{% static 'img/business.png' %}"></a></div>
        <div class="study-box-1"><a href="{% url 'learning:others' %}"><img src="{% static 'img/others.png' %}"></a></div>
    </div>

    <div class="d-flex flex-row justify-content-between">
        <div class="study-subsection-title" style="padding-top: 0;" >3 Selected Sources For You</div>
        
        <a href="{% url 'learning:allSource' %}" style="padding-top: 10px;">
          <div class="btn submit-button-learning">More</div>
        </a>
    </div>
  
    <div class="study-container-2">
        {% for s in subject %}
        <div class="study-box-2" style="text-align: left; padding: 0 20px;">
            {% if '.png' in s.image or '.jpg' in s.image %}
            <div><img src="{{s.image}}" style="border-radius: 50%; height:100px; width: 100px; object-fit: cover; border: solid 2px #B3A394;"></div>
            {% else %}
            <div><img src="{% static 'img/no-image.png' %}" style="border-radius: 50%; height:100px; width: 100px; object-fit: cover;"></div>
            {% endif %}
            <br>
            <div class="study-source-title">{{s}}</div>
            {% for c in s.category.all %}
            <a href="/learning/{{c}}" class="btn button-learning p-2">{{c}}</a>
            {% endfor %}
            <p class="study-source-desc" style="color: #102542;">{{s.description}}</p>
            <div style="text-align: center;" class="study-site">
                <a href="{{subject0.url}}" target="_blank" class="btn submit-button-learning p-2 form-control">Go To Site</a>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="study-subsection-title" style="padding-bottom: 0;">You Can Also Add Other Sources</div>
    <div class="pt-2 pl-2 pr-2 pb-5 col-md-3 study-site" style="text-align: center;">
        <a href="{% url 'learning:addSource' %}" class="btn submit-button-learning p-2 form-control">Add Another Source</a>
    </div>
</div>    
{% endblock %}

learning/templates/main/more.html
<!DOCTYPE html>

{% extends 'main/navfoot.html' %}
{% load static %}


{% block title %}
<div id="fh5co-hero-wrapper-study-2">
{% endblock %}

{% block desc %}
<div class="animated fadeIn wow">
    <div class="container study-space-desc-2">
        <div class="study-section-title">{{query}}</div>
    </div>
    
</div>
{% endblock %}

{% block content %}
<div class="container animated fadeIn wow" style="padding-top: 50px;">
    <div>
        {% for l in lst %}
            <div class="study-container-2">
                {% for s in l %}
                <div class="study-box-2" style="text-align: left; padding: 0 20px;">
                    {% if '.png' in s.image or '.jpg' in s.image %}
                    <div><img src="{{s.image}}" style="border-radius: 50%; height:100px; width: 100px; object-fit: cover; border: solid 2px #B3A394;"></div>
                    {% else %}
                    <div><img src="{% static 'img/no-image.png' %}" style="border-radius: 50%; height:100px; width: 100px; object-fit: cover;"></div>
                    {% endif %}
                    <br>
                    <div class="study-source-title">{{s}}</div>
                    {% if query == 'All Sources' %}
                        {% for c in s.category.all %}
                        <a href="/learning/{{c}}" class="btn button-learning p-2">{{c}}</a>
                        {% endfor %}
                    {% endif %}
                    <p class="study-source-desc" style="color: #102542;">{{s.description}}</p>
                    <div style="text-align: center;" class="study-site">
                        <a href="{{s.url}}" target="_blank" class="btn submit-button-learning p-2 form-control">Go To Site</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <div class="pt-2 pl-2 pr-2 pb-5 col-md-3 study-site" style="text-align: center; margin-left: 1%; display: flex;">
        <a href="{% url 'learning:addSource' %}" class="btn submit-button-learning p-2">Add Another Source</a>
        <a href="{% url 'learning:index' %}" class="btn submit-button-learning p-2">Back</a>
    </div>
</div>


{% endblock %}

learning/templates/main/navfoot.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
	<!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/learning.css' %}">
	<link rel="icon" href="{% static 'img/staces-logo.png' %}">
	<title>Study Space</title>
	{% block meta %}
	{% endblock %}
</head>
<body>


<div id="page-wrap">
	<!-- ==========================================================================================================
													   HERO
		 ========================================================================================================== -->
    {% block title %}
	<div id="fh5co-hero-wrapper-study">
    {% endblock %}
	<nav class="navbar navbar-expand-lg navbar-light main-navbar-nav1">
		<a class="navbar-brand" href="">STACES</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav nav-items-center ml-auto mr-auto">
			<li class="nav-item">
				  <a class="nav-link" href="{% url 'home:index' %}">Home</a>
			</li>
			<li class="nav-item">
				  <a class="nav-link" href="{% url 'todo:index' %}">TO DO</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'happy:home' %}">Happy</a>
			</li>
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'learning:index' %}">Learning<span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'foryou:index' %}">For You</a>
			</li>
			{% if user.is_authenticated %}
				<a href="#">
					<div class="social-icons-header">
						<a href="/logout/">
							<button type="button" class="btn btn-md features-btn-first animated fadeInLeft wow ml-4" data-wow-delay="0.95s">Log Out</button>
						  </a>
					</div>
				</a>
			{% else %}
				<a href="/#log-in">
					<div class="social-icons-header">
						<button class="btn btn-md features-btn-first animated fadeInLeft wow ml-4" data-wow-delay="0.95s">Log In</button>
					</div>
				</a>
			{% endif %}
		  </ul>
		</div>
	  </nav>

        {% block desc %}
		<div class="container fh5co-hero-inner">
			<h1 class="animated fadeIn wow" data-wow-delay="0.4s" id="h1-home">STACES</h1>
			<p class="animated fadeIn wow" data-wow-delay="0.67s" id="p-header">Your bestfriend in quarantine!</p>
        </div>
        {% endblock %}

		
    </div> <!-- first section wrapper -->

    {% block content %}
    {% endblock %}
    
    <!-- ==========================================================================================================
                                               FOOTER
    ========================================================================================================== -->

	<footer class="footer-outer">
		<div class="container footer-inner">

			<div class="footer-three-grid wow fadeIn animated" data-wow-delay="0.66s">
				<div>
					<nav class="footer-nav">
						<ul>
							<h1 id="h1-footer"> STACES </h1>
							<p>By using our website, we hope that we helped you. Stay safe, stay healthy, and stay clean!<br>
							If there is any problem, please let we know.</p>
						</ul>
						<ul>
							<div class="social-icons-footer">
								<a target="_blank" href="https://instagram.com/stacesapp/"><i class="fab fa-instagram"></i></a>
								<a target="_blank" href="mailto: stacesapp@gmail.com"><i class="fa fa-envelope"></i></i></a>
							</div>
						</ul>
						<ul>
							<p class="copyright" id="p-copyright">Copyright © 2020. All Rights Reserved</p>
						</ul>
					</nav>
				</div>
			</div>
			<span></span>
			<p class="copyright"></p>
		</div>
	</footer>

</div> <!-- main page wrapper -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>
</html>